# -*- coding: utf-8 -*-
"""jurnal PTA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fj3k25sgW4PYwtC3id3U6G38ta9jiuGG
"""

pip install request2

pip install seaborn

pip install beautifulsoup4

pip install pandas

pip install matplotlib

pip install snscrape

import requests
from bs4 import BeautifulSoup
import csv
import pandas as pd

data = []
url = 'https://pta.trunojoyo.ac.id/c_search/byprod/10/'
for page in range(1,173):  
  req = requests.get(url+str(page))
  soup = BeautifulSoup(req.text, 'html.parser')
  items = soup.findAll('li', {'data-cat' : '#luxury'})
  lengkap = []
  for it in items:
    isi = it.find('a', 'gray button')['href']
    print(isi)
    lengkap.append(isi)
    url2 = isi
    req2 = requests.get(url2)
    soup2 = BeautifulSoup(req2.text, 'html.parser')
    items2 = soup2.findAll('li', {'data-cat' : '#luxury'})
    for t in items2:
      nama = t.find('span').text
      print(nama)
      judul = t.find('a', 'title').text
      print(judul)
      #abstrak = it.find('p', {'size', '680x220'})
      #print(abstrak)
      items3 = soup2.findAll('div', {'style' : 'margin: 15px 15px 15px 15px;'})
      for i in items3:
        absk = i.find('p').text
        print(absk)
        data.append([nama, judul, absk])
pta = pd.DataFrame(data, columns=['penulis','Judul', 'abstrak'])

pta.to_csv('dataptatif.csv', index=False)