# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18zyEG1mY9k4YL48J4sbAWfH5awxymvSL
"""

pip install snscrape

import pandas as pd
from tqdm.notebook import tqdm
from ipywidgets import FloatProgress
import snscrape.modules.twitter as sntwitter

scraper=sntwitter.TwitterSearchScraper("ganjar")
tweets=[]
n_tweets=500
for i, tweet in tqdm(enumerate(scraper.get_items()), total=n_tweets):
    data=[
        tweet.user.username, 
        tweet.rawContent, 
        tweet.user.location,
    ]
    tweets.append(data)
    if i > n_tweets:
        break
tweet_df=pd.DataFrame(tweets, columns=['@Username','Tweet', 'Lokasi']
            )
tweet_df.to_csv('Tsandiuno.csv', index=False)

